package org.box.fuse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630254
 * 2018-02-01T15:24:28.007+07:00
 * Generated source version: 3.1.5.redhat-630254
 * 
 */
@WebServiceClient(name = "Registration", 
                  wsdlLocation = "http://localhost:40000/box/library/blueprint/register?wsdl",
                  targetNamespace = "http://fuse.box.org/") 
public class Registration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fuse.box.org/", "Registration");
    public final static QName RegistrationPort = new QName("http://fuse.box.org/", "RegistrationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:40000/box/library/blueprint/register?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Registration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:40000/box/library/blueprint/register?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Registration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Registration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Registration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Registration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Registration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Registration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RegistrationPortType
     */
    @WebEndpoint(name = "RegistrationPort")
    public RegistrationPortType getRegistrationPort() {
        return super.getPort(RegistrationPort, RegistrationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationPortType
     */
    @WebEndpoint(name = "RegistrationPort")
    public RegistrationPortType getRegistrationPort(WebServiceFeature... features) {
        return super.getPort(RegistrationPort, RegistrationPortType.class, features);
    }

}
