
package org.box.fuse;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630254
 * 2018-02-01T15:24:27.868+07:00
 * Generated source version: 3.1.5.redhat-630254
 * 
 */
public final class RegistrationPortType_RegistrationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://fuse.box.org/", "Registration");

    private RegistrationPortType_RegistrationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Registration.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Registration ss = new Registration(wsdlURL, SERVICE_NAME);
        RegistrationPortType port = ss.getRegistrationPort();  
        
        {
        System.out.println("Invoking addbook...");
        org.box.fuse.Book _addbook_arg0 = null;
        java.lang.String _addbook__return = port.addbook(_addbook_arg0);
        System.out.println("addbook.result=" + _addbook__return);


        }
        {
        System.out.println("Invoking unregister...");
        java.lang.String _unregister_arg0 = "";
        java.lang.String _unregister__return = port.unregister(_unregister_arg0);
        System.out.println("unregister.result=" + _unregister__return);


        }
        {
        System.out.println("Invoking register...");
        org.box.fuse.Member _register_arg0 = null;
        java.lang.String _register__return = port.register(_register_arg0);
        System.out.println("register.result=" + _register__return);


        }

        System.exit(0);
    }

}
